const JWT_ADMIN_PASSWORD=process.env.JWT_ADMIN_PASSWORD;
const JWT_BUYER_PASSWORD=process.env.JWT_BUYER_PASSWORD;
const JWT_SELLER_PASSWORD=process.env.JWT_SELLER_PASSWORD;

module.exports={
    JWT_ADMIN_PASSWORD,
    JWT_BUYER_PASSWORD,
    JWT_SELLER_PASSWORD
}